### ISSUE TITLE
Not modifying speed with K2 installed

### ISSUE THREAD

**Issue by nullspeaker** [FMR7/faster-robots#1]
I -think- it's related to Krastorio 2 -- I've changed mods a number of times but each time I've had K2 installed I've ran into this issue.
Attached `mod-settings.dat` and `mod-list.json` for a hopefully-complete way to reproduce, if K2 alone is not sufficient.

Attached relevant screenshots as per [similar report](https://mods.factorio.com/mod/faster-robots/discussion/62ca489feda89128166eb17f)
![image](https://user-images.githubusercontent.com/2228057/212875638-0990e7b6-ffd3-4589-b32e-c787bc820642.png)
![image](https://user-images.githubusercontent.com/2228057/212875474-b063b1d8-95e6-46c2-a0bc-d346879e8f3d.png)
![image](https://user-images.githubusercontent.com/2228057/212875508-e07bea20-3373-4b10-80cf-c912f115a3c9.png)
[settings-and-modlist.zip](https://github.com/FMR7/faster-robots/files/10433975/settings-and-modlist.zip)

**Comment by FMR7** [comment]
Hi nhammond129,
Sorry for the delay. I've checked it and updated it. Yes, it was related to Krastorio2, it was overriding the mod.
Thanks for the info.

**Comment by FMR7** [comment]
Hi nhammond129,
Sorry for the delay. I've checked it and updated it. Yes, it was related to Krastorio2, it was overriding the mod.
Thanks for the bug report.
